# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [3]:
print('a.sum() is all type can use \nthen np.sum() and sum(a) using under np and array respectively' )

a.sum() is all type can use 
then np.sum() and sum(a) using under np and array respectively


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [5]:
# 記得先 Import 正確的套件
import numpy as np

In [9]:
A = np.random.random((5, 5))

# formula = (data - data(min))/(data(max)-data(min)) 
#it's called standardization
print(A)

A= (A-A.min()) / (A.max() -A.min())
A

[[0.82575785 0.17195308 0.5933837  0.35440884 0.76087471]
 [0.77835342 0.28164649 0.42855262 0.10044267 0.80300494]
 [0.10694189 0.70124962 0.53176426 0.78797315 0.46977464]
 [0.45775064 0.97267071 0.19338979 0.59069416 0.39110738]
 [0.13632793 0.95647818 0.22098159 0.02798134 0.70171346]]


array([[0.84448553, 0.15240115, 0.59850611, 0.3455395 , 0.77580355],
       [0.79430562, 0.268517  , 0.42402433, 0.07670387, 0.82040046],
       [0.08358362, 0.71268747, 0.53327891, 0.80448857, 0.46765986],
       [0.45493186, 1.        , 0.17509295, 0.5956591 , 0.38438671],
       [0.11469018, 0.98285941, 0.20430023, 0.        , 0.71317847]])

### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [15]:
X = np.random.rand(10)
print('X is \n', X)

X[X.argmax()]=-1
print(X)

X is 
 [0.80528952 0.2239439  0.61374096 0.68529568 0.51547574 0.12746262
 0.55852068 0.36176321 0.95734377 0.68969043]
[ 0.80528952  0.2239439   0.61374096  0.68529568  0.51547574  0.12746262
  0.55852068  0.36176321 -1.          0.68969043]
